import { Routes } from '@angular/router';
import {AutoGeneratedComponent} from '@src/app/auto-generated/auto-generated.component';

export const routes: Routes = [
  {
    path: '',
    redirectTo: '/auto-generated',
    pathMatch: 'full',
  },
  {
    path: 'auto-generated',
    component: AutoGeneratedComponent,
  },
];
