export class Contact {
  id: null;
  registrationNumber: string;
  taxNumber: string;
  classification: string;
  nameSavedAs: string;
  companyId: null;
  companyId2: null;
  companyId3: null;
  leaderId: null;
  ownerId: null;
  leadSourceId: null;
  type: string;
  personTypeId: string;
  contactTypeName: string;
  accountContact: string;
  isBank: true;
  isBuyer: true;
  isSupplier: true;
  isOurCompany: true;
  costCenter: string;
  codeGK: string;
  courtName: string;
  courtSubmissionNumber: string;
  shareCapital: null;
  isTaxablePerson: true;
  chosenSendingAddress: null;
  companyName: string;
  companyNameShort: string;
  companyNameShowAs: string;
  firstName: string;
  lastName: string;
  gender: string;
  function: string;
  title: string;
  prefix: string;
  suffix: string;
  mobileNumber: string;
  businessAddress: string;
  businessCity: string;
  businessCountry: string;
  businessCountryCode: string;
  businessMailbox: string;
  businessPostalCode: string;
  businessFederalState: string;
  businessStreet: string;
  businessFax: string;
  businessWebsite: string;
  businessNumberCentral: string;
  businessNumber: string;
  businessNumber2: string;
  telex: string;
  homeAddress: string;
  homeCity: string;
  homeCountry: string;
  homeCountryCode: string;
  homeMailbox: string;
  homePostalCode: string;
  homeFederalState: string;
  homeStreet: string;
  homeFax: string;
  homeNumber: string;
  homeNumber2: string;
  otherAddress: string;
  otherCity: string;
  otherCountry: string;
  otherCountryCode: string;
  otherMailbox: string;
  otherPostalCode: string;
  otherFederalState: string;
  otherStreet: string;
  otherFax: string;
  otherNumber: string;
  comment: string;
  email1: string;
  email2: string;
  email3: string;
  inRecycleBin: true;
  languageCode: string;
  currencyCode: string;
  legalFormId: string;
  importanceId: string;
  responsibilityId: string;
  birthday: Date | string;
  choiceAddress: string;
  choicePhoneNumber1: string;
  choicePhoneNumber2: string;
  choicePhoneNumber3: string;
  choicePhoneNumber4: string;
  choicePhoneNumber5: string;
  choicePhoneNumber6: string;
  choicePhoneNumber7: string;
  choicePhoneNumber8: string;
  choiceEmail: string;
  department: string;
  parentId: null;
  accountId: null;
  skd: string;
  employeeFrom: null;
  employeeTo: null;
  businessNumberCentralNum: string;
  businessNumberNum: string;
  businessNumber2Num: string;
  businessFaxNum: string;
  homeNumberNum: string;
  homeNumber2Num: string;
  homeFaxNum: string;
  otherNumberNum: string;
  mobileNumberNum: string;
  otherFaxNum: string;
  primaryNumberNum: string;
  employed1: null;
  employedDateTime1: Date | string;
  employed2: null;
  employedDateTime2: Date | string;
  turnover1: null;
  turnoverDateTime1: Date | string;
  turnover2: null;
  turnoverDateTime2: Date | string;
  profit1: null;
  profitDateTime1: Date | string;
  profit2: null;
  profitDateTime2: Date | string;
  creditRating1: null;
  creditRatingDateTime1: Date | string;
  creditRating2: null;
  creditRatingDateTime2: Date | string;
  customShared1Id: null;
  customShared2Id: null;
  custom1Id: null;
  custom2Id: null;
  customDateTime1: Date | string;
  customDateTime2: Date | string;
  customDateTime3: Date | string;
  customDateTime4: Date | string;
  customText1: string;
  customText2: string;
  customText3: string;
  customText4: string;
  customNum1: null;
  customNum2: null;
  customNum3: null;
  customNum4: null;
  customBool1: true;
  customBool2: true;
  customBool3: true;
  customBool4: true;
  isActive: true;
  isEmployee: true;
  recNew: true;
  recUnofficial: true;
  createdBy: null;
  createdOn: Date | string;
  modifiedBy: null;
  modifiedOn: Date | string;
  createdBy_copy: null;
  modifiedBy_copy: null;
  isGuest: true;
  isPantheonSynced: true;
  pantheonId: null;
  name: string;
  email: string;
  address: string;
  parentName: string;
  parentType: string;
  category: string;
  validate: true;
  operations: ('read'|'write'|'delete'|'full')[] = [];
  constructor() {}
}
